[package]
name = "rrss2imap"
version = "0.1.0"
authors = ["Nicolas Delsaux <nicolas.delsaux@zenika.com>"]

[dependencies]
log = "0.4"
flexi_logger = "0.9.0"
# Used for parsing command line args
structopt = "0.2"
# Used for reading/writing config file
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.24"

[dev-dependencies]
assert_cli = "0.5.4"