[package]
name = "rrss2imap"
version = "0.1.0"
authors = ["Nicolas Delsaux <nicolas.delsaux@zenika.com>"]

[dependencies]
log = "0.4"
flexi_logger = "0.9"
# Used for parsing command line args
structopt = "0.2"
# Used for reading/writing config file
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
# Used for import/export
treexml = "0.7"
# Used to get feed entries (and images, when it will be possible)
requests = "0.0"
# Used to parse Atom/RSS feed
feed-rs = "0.1"
chrono = { version = "0.4", features = ["serde"] }
# A good html parser to allow generation of valid mail messages
html5ever = "0.22"
# And an imap connector, obviously
imap = "0.8"
# Used to generate html text messages from initial entries
tera = "0.11"
# Allows to easily start tera
lazy_static = "1.1"

[dev-dependencies]
assert_cli = "0.6"