[package]
name = "rrss2imap"
version = "0.1.0"
authors = ["Nicolas Delsaux <nicolas.delsaux@zenika.com>"]

[dependencies]
structopt = "0.2"
log = "0.4"
flexi_logger = "0.9.0"
serde-xml-rs = "0.2.1"
serde = "1.0.71"

[dev-dependencies]
assert_cli = "0.5.4"